spring:
  datasource:
    url: jdbc:h2:mem:messagesdb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: true
server:
  port: 7000